//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhonesDBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Param
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Param()
        {
            this.Phones = new HashSet<Phone>();
        }
    
        public int ParamsId { get; set; }
        public string CPU { get; set; }
        public double ScreenDiagonal { get; set; }
        public string Color { get; set; }
        public int Capacity { get; set; }
        public int Memory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phone> Phones { get; set; }
    }
}
